### PR TITLE
fix csv header issue

### PR DESCRIPTION
**Pull request by ChicoXYC**
there is an error in original sample data, and its not good for codes demo.

### CODE REVIEW

**Comment by hupili** [comment]
what is changed? do you remove the header in the new version?

**Comment by ChicoXYC** [comment]
In original header, the place of  location and likes are wrong.
And also I remove the header so that can demo read csv with adding a header

**Comment by hupili** [comment]
its better to have header. if the header is wrong, you can demo how to fix it after loading. please add this pointer to the data cleaning section.

**Comment by hupili** [comment]
having header is part of CSV convention. That makes the file self descriptive.

**Comment by ChicoXYC** [comment]
@update. add restaurants links and poi_id. total data volume:3k

**Comment by ChicoXYC** [comment]
@hupili remove tips of scraping from open book to scraping notebook

**Pull request merged**
