### PR TITLE
upload open rice example

### PR DESCRIPTION
**Pull request by ChicoXYC**

### CODE REVIEW

**Comment by hupili** [comment]
@ChicoXYC  is this the updated dataset? i.e. data from recently executed scripts.

The number of items is very small in previous, please crawl more pages, or loosen the search criteria to get more results.

**Comment by ChicoXYC** [comment]
@hupili no matter how you lose the search criteria,  open rice only display 17 pages of the content.

**Comment by hupili** [comment]
You can try to drill down and assemble the results. Use [multiple layer loop](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-03.md#multiple-loop) to get search results of different combinations of `time range, geo region, price range, ...`

**Comment by ChicoXYC** [comment]
@hupili update. I don't use multiple layer loop to scrape because open rice encodes those parameters into the format like `dishId=1014&districtId=2008`, Its tricky we need to figure out those things first. Therefore I update a new version that scrapes a day's `full time` periods restaurants, after removing the duplicates, the data volume is 772.

**Comment by hupili** [comment]
The district IDs can be obtained from the page source code:

screen shot 2018-09-24 at 2 32 46 pm


This is good scraper example. After this PR is finished, please add it to further reading of ch5. Then we are one step beyond simple scrapers.

**Comment by ChicoXYC** [comment]
@hupili update, for more info, please see the notebook. Thanks

**Comment by hupili** [comment]
Looks good. Please add table header.

Another question is, are there other columns except for the current 5?


https://github.com/ChicoXYC/python-for-data-and-media-communication/blob/master/scraper-examples/open_rice/openrice.ipynb

**Comment by ChicoXYC** [comment]
@hupili another 3 features we can scrape are:
1. favorites/收藏
2. discount/优惠
3. highlight/热门
image

Do you need me to scrape it again? If so, in order to reduce the time of running codes, can you help me to imporve the codes and omit the duplicates so that we can save more time?

**Comment by hupili** [comment]
yes. let improve and iterate. how long does it take last time?

**Comment by hupili** [comment]
do we already have the 513食評 and the emoji icons number in the dataset?

**Comment by hupili** [comment]
there is little room to improve the scraping if list page. For the scraping of detailed page, the URLs can be dedulicafed though. Can you make a smaller sized sample first after adding those new fields?

**Comment by ChicoXYC** [comment]
1. last time it cost 12 hours.
2. doesn't include 513食評 but contains the emoji icons number(only big one).
3. Yes, the problem is some url they don't have 17 pages of content, so I need to improve the judgment to save more time.

>a smaller sized sample

You mean like I first scrape several pages that includes those additional informations, then discuss to preceed further?

**Comment by hupili** [comment]
> doesn't include 513食評 but contains the emoji icons number(only big one).

Please try to include this field. number of comments is also useful.

**Comment by hupili** [comment]
> You mean like I first scrape several pages that includes those additional informations, then discuss to preceed further?

Yes.

**Comment by ChicoXYC** [comment]
@hupili update sir!

**Comment by hupili** [comment]
@ChicoXYC  The new sample is nice! We will have a better demo for preprocessing with so many fields. Well done!

You can start to collect the full dataset. It seems little room for optimisation for this task. The only thing you can try is to distribute the work loads to multiple machines. For example, open 5 machines in lab, each collects 4000 entries, then you assemble those CSVs into one. That could be much faster.

**Comment by hupili** [comment]
**important** A code level revision is needed.

Let's stick to the [list-of-dict](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-05.md#data-structure) way to organise the code. You can checkout my imdb example. It is better to loop over items and then loop over their respective attributes. Let's correct this practice before most of other students get hands on this chapter. The current way of crawling attributes first is error prone, especially when some attributes of some items are missing. Many students ran into this error last time. 

Another upside is that, if you store data in list-of-dict style, it takes only one line to store in CSV with `pandas`.

Considering this may be example for week05/06, when people have not learned `pandas` yet, you can consider to store the data in [list-of-list](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-05.md#data-structure) style, so it takes one line for `csv.writerows` ("s") to output the whole dataset to CSV.

**Comment by ChicoXYC** [comment]
@hupili OK right

**Comment by ChicoXYC** [comment]
@hupili revised. the reason why i store data in list of list is that i need to write a csv in the loop, so that when it breaks, there is still some data instead of losing all.

**Comment by hupili** [comment]
Is [this notebook](http://nbviewer.jupyter.org/github/hupili/python-for-data-and-media-communication/blob/efb12cdcceb2779ad1487a63fcb397f71946c6b1/scraper-examples/open_rice/openrice_sample.ipynb) the latest version?  Is so, the practice is still not corrected. Let's try best not to demo the "attribute-first" approach. Even if you use a lot `if-else` to guard the extracted result, the solution is not intuitive. Also, the `countries` extraction is outside of the item loop. We need to stick to the "item-first" approach. Actually, this approach is also how frontend developers build their pages. So the way of building and the way of scraping are coherent.

Please reorganise into this mode. I'll add a section to our book for further elaboration.

```python
data = []
for myitem in myitems:
    title = ???
    like = ???
    location = ???
    ...
    data.append([title, like, location, ...])

...
csv.writerows(data) # one line is enough for the output.
```

**Comment by hupili** [comment]
@ChicoXYC , here is the relevant note on [item-first](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-05.md#item-first-vs-attribute-first) approach.

Also the way of [handling missing data](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-05.md#deal-with-missing-data-in-scraping) can be improved.

Please leave your questions if those two sub sections are not clear.

**Comment by hupili** [comment]
👍  [current notebook](https://github.com/hupili/python-for-data-and-media-communication/blob/a5985d4bf42ad91536c04c6e2f936118194d44df/scraper-examples/open_rice/openrice_sample.ipynb) is much better . I'm going to merge this one. Please move forward to collecting the 20K entries.

**Pull request merged**
