### PR TITLE
github contribution example

### PR DESCRIPTION
**Pull request by ChicoXYC**

### CODE REVIEW

**Comment by hupili** [comment]
https://github.com/ChicoXYC/python-for-data-and-media-communication/blob/master/scraper-examples/github_contributions/github_contributions.ipynb

**Comment by hupili** [comment]
Following codes seems unused.

```python
            contribution = data.find(data['data-count'])
            date = data.find(data['data-date'])
```

**Comment by hupili** [comment]
Please rename `subjects` to `contributions`. Although you can name variables in any syntactically correct way, giving meaningful names is a good convention. It will be easier for readers to comprehend the logics.

**Comment by ChicoXYC** [comment]
@hupili update 😄

**Comment by ChicoXYC** [comment]
@hupili yes, it can simply use `writerows`, I add it as a quick test.

**Comment by hupili** [comment]
I mean, you use the writerows version as first solution (BCP). Then give your original version in comments as alternatives

**Comment by ChicoXYC** [comment]
@hupili update

**Pull request merged**
